<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BulkHunterLeadsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        DB::table('buyer_leads')->truncate();

        $leads = [
            // WHALE Category - Major Restaurant Chains & Large Businesses
            [
                'abn' => '33000028864',
                'business_name' => 'McDonald\'s Australia Limited',
                'trading_name' => 'McDonald\'s',
                'category' => 'Fast Food Restaurant Chain',
                'address' => '21 Fountain St, Alexandria NSW 2015',
                'postcode' => '2015',
                'state' => 'NSW',
                'phone' => '02 9875 7100',
                'email' => 'procurement@mcdonalds.com.au',
                'website' => 'https://mcdonalds.com.au',
                'employee_count' => 105000,
                'business_type' => 'Restaurant Chain',
                'weekly_volume_estimate' => 50000,
                'monthly_spend_estimate' => 2500000,
                'google_rating' => 3.8,
                'google_reviews_count' => 15420,
                'current_supplier' => 'Multiple National Distributors',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Need more sustainable packaging options',
                'buyer_persona' => 'Corporate Procurement Team',
                'decision_maker' => 'National Procurement Manager',
                'size_classification' => 'WHALE',
                'buying_cycle' => 'Weekly',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Daily to 970+ locations',
                'special_requirements' => 'Strict quality standards, halal options required',
                'status' => 'QUALIFIED',
                'final_score' => 95,
            ],
            [
                'abn' => '75000012342',
                'business_name' => 'Woolworths Group Limited',
                'trading_name' => 'Woolworths Supermarkets',
                'category' => 'Supermarket Chain',
                'address' => '1 Woolworths Way, Bella Vista NSW 2153',
                'postcode' => '2153',
                'state' => 'NSW',
                'phone' => '02 8885 0000',
                'email' => 'supplier.relations@woolworths.com.au',
                'website' => 'https://woolworthsgroup.com.au',
                'employee_count' =>195000,
                'business_type' => 'Retail Supermarket',
                'weekly_volume_estimate' => 200000,
                'monthly_spend_estimate' => 10000000,
                'google_rating' => 4.0,
                'google_reviews_count' => 28500,
                'current_supplier' => 'Direct from farms & distributors',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Looking for more local suppliers',
                'buyer_persona' => 'Category Buying Team',
                'decision_maker' => 'Fresh Produce Category Manager',
                'size_classification' => 'WHALE',
                'buying_cycle' => 'Daily',
                'payment_terms' => '45 days',
                'delivery_requirements' => 'Multiple daily deliveries',
                'special_requirements' => 'Freshness guarantee, traceability required',
                'status' => 'QUALIFIED',
                'final_score' => 98,
            ],
            [
                'abn' => '88000014675',
                'business_name' => 'Coles Group Limited',
                'trading_name' => 'Coles Supermarkets',
                'category' => 'Supermarket Chain',
                'address' => '800 Toorak Rd, Hawthorn East VIC 3123',
                'postcode' => '3123',
                'state' => 'VIC',
                'phone' => '03 9829 3111',
                'email' => 'supplier.portal@coles.com.au',
                'website' => 'https://colesgroup.com.au',
                'employee_count' =>120000,
                'business_type' => 'Retail Supermarket',
                'weekly_volume_estimate' => 180000,
                'monthly_spend_estimate' => 9000000,
                'google_rating' => 3.9,
                'google_reviews_count' => 24300,
                'current_supplier' => 'Multiple suppliers via Coles Direct',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Seeking better pricing on organics',
                'buyer_persona' => 'Strategic Sourcing Team',
                'decision_maker' => 'Head of Fresh Produce',
                'size_classification' => 'WHALE',
                'buying_cycle' => 'Daily',
                'payment_terms' => '30-60 days',
                'delivery_requirements' => 'DC distribution model',
                'special_requirements' => 'EDI integration required',
                'status' => 'ENRICHED',
                'final_score' => 96,
            ],

            // BIG Category - Large Restaurants & Hotels
            [
                'abn' => '41082744537',
                'business_name' => 'Rockpool Dining Group',
                'trading_name' => 'Rockpool Bar & Grill',
                'category' => 'Fine Dining Restaurant Group',
                'address' => '66 Hunter Street, Sydney NSW 2000',
                'postcode' => '2000',
                'state' => 'NSW',
                'phone' => '02 8078 1900',
                'email' => 'purchasing@rockpool.com',
                'website' => 'https://rockpooldininggroup.com',
                'employee_count' =>2000,
                'business_type' => 'Restaurant Group',
                'weekly_volume_estimate' => 8000,
                'monthly_spend_estimate' => 400000,
                'google_rating' => 4.5,
                'google_reviews_count' => 3420,
                'current_supplier' => 'Sydney Markets Direct',
                'unhappy_with_supplier' => true,
                'supplier_pain_points' => 'Inconsistent quality, late deliveries',
                'buyer_persona' => 'Executive Chef & Procurement',
                'decision_maker' => 'Group Executive Chef',
                'size_classification' => 'BIG',
                'buying_cycle' => '2-3 times weekly',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Early morning before 6am',
                'special_requirements' => 'Premium quality only',
                'status' => 'NEW',
                'final_score' => 85,
            ],
            [
                'abn' => '49003668927',
                'business_name' => 'Crown Resorts Limited',
                'trading_name' => 'Crown Sydney',
                'category' => 'Hotel & Casino',
                'address' => 'One Barangaroo Ave, Barangaroo NSW 2000',
                'postcode' => '2000',
                'state' => 'NSW',
                'phone' => '02 8871 7171',
                'email' => 'procurement@crownsydney.com.au',
                'website' => 'https://crownsydney.com.au',
                'employee_count' =>8000,
                'business_type' => 'Hospitality & Entertainment',
                'weekly_volume_estimate' => 15000,
                'monthly_spend_estimate' => 750000,
                'google_rating' => 4.3,
                'google_reviews_count' => 5670,
                'current_supplier' => 'Multiple premium suppliers',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Need better organic options',
                'buyer_persona' => 'F&B Procurement Director',
                'decision_maker' => 'Director of Food & Beverage',
                'size_classification' => 'BIG',
                'buying_cycle' => 'Daily',
                'payment_terms' => '45 days',
                'delivery_requirements' => 'Multiple daily deliveries',
                'special_requirements' => 'Premium & exotic produce',
                'status' => 'QUALIFIED',
                'final_score' => 88,
            ],
            [
                'abn' => '36082034283',
                'business_name' => 'Merivale Group',
                'trading_name' => 'Merivale',
                'category' => 'Hospitality Group',
                'address' => '2 Reiby Pl, Sydney NSW 2000',
                'postcode' => '2000',
                'state' => 'NSW',
                'phone' => '02 9114 7300',
                'email' => 'suppliers@merivale.com',
                'website' => 'https://merivale.com',
                'employee_count' =>4500,
                'business_type' => 'Restaurant & Bar Group',
                'weekly_volume_estimate' => 12000,
                'monthly_spend_estimate' => 600000,
                'google_rating' => 4.4,
                'google_reviews_count' => 8900,
                'current_supplier' => 'Zupply',
                'unhappy_with_supplier' => true,
                'supplier_pain_points' => 'High fees, limited product range',
                'buyer_persona' => 'Central Purchasing Team',
                'decision_maker' => 'Head of Procurement',
                'size_classification' => 'BIG',
                'buying_cycle' => 'Daily',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Multiple venue delivery',
                'special_requirements' => '75+ venues across Sydney',
                'status' => 'NEW',
                'final_score' => 87,
            ],

            // MEDIUM Category - Mid-size Restaurants & Cafes
            [
                'abn' => '61614299637',
                'business_name' => 'Bills Australia Pty Ltd',
                'trading_name' => 'Bills',
                'category' => 'Cafe Restaurant Chain',
                'address' => '79 Hall St, Bondi Beach NSW 2026',
                'postcode' => '2026',
                'state' => 'NSW',
                'phone' => '02 9360 4762',
                'email' => 'orders@bills.com.au',
                'website' => 'https://bills.com.au',
                'employee_count' =>250,
                'business_type' => 'Cafe Restaurant',
                'weekly_volume_estimate' => 2000,
                'monthly_spend_estimate' => 100000,
                'google_rating' => 4.6,
                'google_reviews_count' => 2340,
                'current_supplier' => 'Local Markets',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Weekend delivery issues',
                'buyer_persona' => 'Restaurant Manager',
                'decision_maker' => 'Operations Manager',
                'size_classification' => 'MEDIUM',
                'buying_cycle' => '3 times weekly',
                'payment_terms' => '14 days',
                'delivery_requirements' => 'Morning delivery',
                'special_requirements' => 'Organic focus',
                'status' => 'ENRICHED',
                'final_score' => 72,
            ],
            [
                'abn' => '85165478234',
                'business_name' => 'Guzman y Gomez Mexican Kitchen',
                'trading_name' => 'GYG',
                'category' => 'Fast Casual Restaurant',
                'address' => '175 King St, Newtown NSW 2042',
                'postcode' => '2042',
                'state' => 'NSW',
                'phone' => '02 9519 0444',
                'email' => 'suppliers@gyg.com.au',
                'website' => 'https://guzmanygomez.com.au',
                'employee_count' =>6000,
                'business_type' => 'Fast Food Chain',
                'weekly_volume_estimate' => 5000,
                'monthly_spend_estimate' => 250000,
                'google_rating' => 4.2,
                'google_reviews_count' => 4560,
                'current_supplier' => 'National Food Service',
                'unhappy_with_supplier' => true,
                'supplier_pain_points' => 'Freshness issues with current supplier',
                'buyer_persona' => 'Supply Chain Manager',
                'decision_maker' => 'National Supply Manager',
                'size_classification' => 'MEDIUM',
                'buying_cycle' => '2 times weekly',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Multi-site delivery',
                'special_requirements' => 'Specific Mexican ingredients',
                'status' => 'NEW',
                'final_score' => 78,
            ],
            [
                'abn' => '92643812456',
                'business_name' => 'The Grounds of Alexandria',
                'trading_name' => 'The Grounds',
                'category' => 'Cafe Restaurant & Events',
                'address' => '2 Huntley St, Alexandria NSW 2015',
                'postcode' => '2015',
                'state' => 'NSW',
                'phone' => '02 9699 2225',
                'email' => 'kitchen@thegrounds.com.au',
                'website' => 'https://thegrounds.com.au',
                'employee_count' =>450,
                'business_type' => 'Restaurant & Event Space',
                'weekly_volume_estimate' => 3000,
                'monthly_spend_estimate' => 150000,
                'google_rating' => 4.3,
                'google_reviews_count' => 12300,
                'current_supplier' => 'Bidfood',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Looking for more artisanal products',
                'buyer_persona' => 'Head Chef',
                'decision_maker' => 'Executive Chef',
                'size_classification' => 'MEDIUM',
                'buying_cycle' => 'Daily',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Early morning',
                'special_requirements' => 'Farm to table focus',
                'status' => 'QUALIFIED',
                'final_score' => 75,
            ],

            // SMALL Category - Small Restaurants & Cafes
            [
                'abn' => '78234567891',
                'business_name' => 'Bella Vista Italian Restaurant',
                'trading_name' => 'Bella Vista',
                'category' => 'Italian Restaurant',
                'address' => '45 Norton St, Leichhardt NSW 2040',
                'postcode' => '2040',
                'state' => 'NSW',
                'phone' => '02 9560 7788',
                'email' => 'info@bellavista.com.au',
                'website' => null,
                'employee_count' =>15,
                'business_type' => 'Restaurant',
                'weekly_volume_estimate' => 300,
                'monthly_spend_estimate' => 15000,
                'google_rating' => 4.7,
                'google_reviews_count' => 432,
                'current_supplier' => 'Cash & Carry',
                'unhappy_with_supplier' => true,
                'supplier_pain_points' => 'No delivery, quality inconsistent',
                'buyer_persona' => 'Owner Chef',
                'decision_maker' => 'Owner',
                'size_classification' => 'SMALL',
                'buying_cycle' => 'Twice weekly',
                'payment_terms' => 'COD',
                'delivery_requirements' => 'Morning preferred',
                'special_requirements' => 'Italian specialty items',
                'status' => 'NEW',
                'final_score' => 45,
            ],
            [
                'abn' => '65432198765',
                'business_name' => 'Green Bean Cafe',
                'trading_name' => 'Green Bean',
                'category' => 'Cafe',
                'address' => '123 King St, Newtown NSW 2042',
                'postcode' => '2042',
                'state' => 'NSW',
                'phone' => '02 9517 2233',
                'email' => 'orders@greenbean.com.au',
                'website' => 'https://greenbeancafe.com.au',
                'employee_count' =>8,
                'business_type' => 'Cafe',
                'weekly_volume_estimate' => 150,
                'monthly_spend_estimate' => 7500,
                'google_rating' => 4.8,
                'google_reviews_count' => 234,
                'current_supplier' => 'Local Grocer',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Limited organic options',
                'buyer_persona' => 'Cafe Manager',
                'decision_maker' => 'Owner',
                'size_classification' => 'SMALL',
                'buying_cycle' => 'Weekly',
                'payment_terms' => '7 days',
                'delivery_requirements' => 'Flexible',
                'special_requirements' => 'Organic & vegan focus',
                'status' => 'ENRICHED',
                'final_score' => 38,
            ],
            [
                'abn' => '98765432109',
                'business_name' => 'Sydney Kebab House',
                'trading_name' => 'Kebab House',
                'category' => 'Takeaway Restaurant',
                'address' => '789 George St, Sydney NSW 2000',
                'postcode' => '2000',
                'state' => 'NSW',
                'phone' => '02 9267 8899',
                'email' => null,
                'website' => null,
                'employee_count' =>6,
                'business_type' => 'Fast Food',
                'weekly_volume_estimate' => 200,
                'monthly_spend_estimate' => 10000,
                'google_rating' => 4.1,
                'google_reviews_count' => 567,
                'current_supplier' => 'Cash Markets',
                'unhappy_with_supplier' => true,
                'supplier_pain_points' => 'Unreliable, no invoice system',
                'buyer_persona' => 'Owner Operator',
                'decision_maker' => 'Owner',
                'size_classification' => 'SMALL',
                'buying_cycle' => '3 times weekly',
                'payment_terms' => 'Cash',
                'delivery_requirements' => 'Any time',
                'special_requirements' => 'Halal certified',
                'status' => 'NEW',
                'final_score' => 42,
            ],

            // More realistic Sydney businesses
            [
                'abn' => '47098123456',
                'business_name' => 'Harris Farm Markets',
                'trading_name' => 'Harris Farm',
                'category' => 'Fresh Food Retailer',
                'address' => '1 Sunnyside Rd, Mosman NSW 2088',
                'postcode' => '2088',
                'state' => 'NSW',
                'phone' => '02 9969 1636',
                'email' => 'buyers@harrisfarm.com.au',
                'website' => 'https://harrisfarm.com.au',
                'employee_count' =>2000,
                'business_type' => 'Fresh Food Retail Chain',
                'weekly_volume_estimate' => 25000,
                'monthly_spend_estimate' => 1250000,
                'google_rating' => 4.4,
                'google_reviews_count' => 3456,
                'current_supplier' => 'Direct from farms',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Seeking more local suppliers',
                'buyer_persona' => 'Category Buyers',
                'decision_maker' => 'Head of Buying',
                'size_classification' => 'BIG',
                'buying_cycle' => 'Daily',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Store direct delivery',
                'special_requirements' => '25+ stores across NSW',
                'status' => 'QUALIFIED',
                'final_score' => 82,
            ],
            [
                'abn' => '52178945623',
                'business_name' => 'Fratelli Fresh',
                'trading_name' => 'Fratelli Fresh',
                'category' => 'Italian Food Retailer',
                'address' => '7 Bridge St, Sydney NSW 2000',
                'postcode' => '2000',
                'state' => 'NSW',
                'phone' => '02 8221 0021',
                'email' => 'purchasing@fratellifresh.com.au',
                'website' => 'https://fratellifresh.com.au',
                'employee_count' =>500,
                'business_type' => 'Specialty Food Retail',
                'weekly_volume_estimate' => 5000,
                'monthly_spend_estimate' => 250000,
                'google_rating' => 4.5,
                'google_reviews_count' => 2890,
                'current_supplier' => 'Italian importers',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Need more local fresh produce',
                'buyer_persona' => 'Procurement Team',
                'decision_maker' => 'Chief Buyer',
                'size_classification' => 'MEDIUM',
                'buying_cycle' => 'Daily',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Multi-location',
                'special_requirements' => 'Premium Italian products',
                'status' => 'ENRICHED',
                'final_score' => 73,
            ],
            [
                'abn' => '63289456123',
                'business_name' => 'Bondi Trattoria',
                'trading_name' => 'Bondi Trattoria',
                'category' => 'Italian Restaurant',
                'address' => '34 Campbell Parade, Bondi Beach NSW 2026',
                'postcode' => '2026',
                'state' => 'NSW',
                'phone' => '02 9365 4303',
                'email' => 'info@bonditrattoria.com.au',
                'website' => 'https://bonditrattoria.com.au',
                'employee_count' =>35,
                'business_type' => 'Restaurant',
                'weekly_volume_estimate' => 800,
                'monthly_spend_estimate' => 40000,
                'google_rating' => 4.2,
                'google_reviews_count' => 1234,
                'current_supplier' => 'Multiple local suppliers',
                'unhappy_with_supplier' => true,
                'supplier_pain_points' => 'Too many suppliers to manage',
                'buyer_persona' => 'Head Chef',
                'decision_maker' => 'Executive Chef',
                'size_classification' => 'MEDIUM',
                'buying_cycle' => '3 times weekly',
                'payment_terms' => '14 days',
                'delivery_requirements' => 'Early morning',
                'special_requirements' => 'Fresh pasta & seafood',
                'status' => 'NEW',
                'final_score' => 68,
            ],
            [
                'abn' => '74512389456',
                'business_name' => 'Doyles Seafood Restaurant',
                'trading_name' => 'Doyles',
                'category' => 'Seafood Restaurant',
                'address' => '11 Marine Parade, Watsons Bay NSW 2030',
                'postcode' => '2030',
                'state' => 'NSW',
                'phone' => '02 9337 1350',
                'email' => 'orders@doyles.com.au',
                'website' => 'https://doyles.com.au',
                'employee_count' =>120,
                'business_type' => 'Restaurant Group',
                'weekly_volume_estimate' => 2500,
                'monthly_spend_estimate' => 125000,
                'google_rating' => 4.0,
                'google_reviews_count' => 3456,
                'current_supplier' => 'Sydney Fish Market',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Need wider variety',
                'buyer_persona' => 'Purchasing Manager',
                'decision_maker' => 'Operations Director',
                'size_classification' => 'MEDIUM',
                'buying_cycle' => 'Daily',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Multiple locations',
                'special_requirements' => 'Premium seafood focus',
                'status' => 'QUALIFIED',
                'final_score' => 71,
            ],
            [
                'abn' => '85623147890',
                'business_name' => 'Paddy\'s Markets',
                'trading_name' => 'Paddy\'s Markets',
                'category' => 'Fresh Produce Market',
                'address' => '9 Hay St, Haymarket NSW 2000',
                'postcode' => '2000',
                'state' => 'NSW',
                'phone' => '02 9325 6200',
                'email' => 'vendors@paddysmarkets.com.au',
                'website' => 'https://paddysmarkets.com.au',
                'employee_count' =>250,
                'business_type' => 'Market Operator',
                'weekly_volume_estimate' => 30000,
                'monthly_spend_estimate' => 1500000,
                'google_rating' => 4.1,
                'google_reviews_count' => 5678,
                'current_supplier' => 'Multiple vendors',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Coordination challenges',
                'buyer_persona' => 'Market Management',
                'decision_maker' => 'General Manager',
                'size_classification' => 'BIG',
                'buying_cycle' => 'Continuous',
                'payment_terms' => 'Vendor dependent',
                'delivery_requirements' => 'Market hours',
                'special_requirements' => '200+ vendors',
                'status' => 'CONTACTED',
                'final_score' => 80,
            ],
            [
                'abn' => '96734258901',
                'business_name' => 'About Life',
                'trading_name' => 'About Life',
                'category' => 'Health Food Store',
                'address' => '25 Glebe Point Rd, Glebe NSW 2037',
                'postcode' => '2037',
                'state' => 'NSW',
                'phone' => '02 9660 3712',
                'email' => 'orders@aboutlife.com.au',
                'website' => 'https://aboutlife.com.au',
                'employee_count' =>150,
                'business_type' => 'Health Food Retail',
                'weekly_volume_estimate' => 4000,
                'monthly_spend_estimate' => 200000,
                'google_rating' => 4.6,
                'google_reviews_count' => 1890,
                'current_supplier' => 'Organic wholesalers',
                'unhappy_with_supplier' => true,
                'supplier_pain_points' => 'Limited local organic options',
                'buyer_persona' => 'Category Manager',
                'decision_maker' => 'Head of Purchasing',
                'size_classification' => 'MEDIUM',
                'buying_cycle' => '3 times weekly',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'Morning delivery',
                'special_requirements' => '100% organic certified',
                'status' => 'NEW',
                'final_score' => 74,
            ],
            [
                'abn' => '18456789234',
                'business_name' => 'Romeo\'s Food Hall',
                'trading_name' => 'Romeo\'s IGA',
                'category' => 'Independent Supermarket',
                'address' => '247 Norton St, Leichhardt NSW 2040',
                'postcode' => '2040',
                'state' => 'NSW',
                'phone' => '02 9560 7899',
                'email' => 'buyers@romeosfoodhall.com',
                'website' => 'https://romeos.net.au',
                'employee_count' =>85,
                'business_type' => 'Supermarket',
                'weekly_volume_estimate' => 6000,
                'monthly_spend_estimate' => 300000,
                'google_rating' => 4.3,
                'google_reviews_count' => 1567,
                'current_supplier' => 'IGA Distribution',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Want more local products',
                'buyer_persona' => 'Store Manager',
                'decision_maker' => 'Owner',
                'size_classification' => 'MEDIUM',
                'buying_cycle' => 'Daily',
                'payment_terms' => '30 days',
                'delivery_requirements' => 'DC + Direct',
                'special_requirements' => 'Italian specialties',
                'status' => 'QUALIFIED',
                'final_score' => 76,
            ],
            [
                'abn' => '29567890345',
                'business_name' => 'The Star Sydney',
                'trading_name' => 'The Star',
                'category' => 'Casino & Entertainment',
                'address' => '80 Pyrmont St, Pyrmont NSW 2009',
                'postcode' => '2009',
                'state' => 'NSW',
                'phone' => '02 9777 9000',
                'email' => 'procurement@star.com.au',
                'website' => 'https://star.com.au',
                'employee_count' =>8000,
                'business_type' => 'Casino & Hotels',
                'weekly_volume_estimate' => 20000,
                'monthly_spend_estimate' => 1000000,
                'google_rating' => 3.9,
                'google_reviews_count' => 8901,
                'current_supplier' => 'Multiple premium suppliers',
                'unhappy_with_supplier' => false,
                'supplier_pain_points' => 'Complex ordering process',
                'buyer_persona' => 'F&B Procurement',
                'decision_maker' => 'Director of F&B',
                'size_classification' => 'BIG',
                'buying_cycle' => 'Daily',
                'payment_terms' => '45 days',
                'delivery_requirements' => '24/7 operation',
                'special_requirements' => '20+ restaurants & bars',
                'status' => 'CONVERTED',
                'final_score' => 89,
            ],
        ];

        // Insert all leads
        foreach ($leads as $lead) {
            $lead['discovered_at'] = Carbon::now()->subDays(rand(1, 30));
            $lead['created_at'] = $lead['discovered_at'];
            $lead['updated_at'] = Carbon::now();

            // Add some enrichment dates for ENRICHED/QUALIFIED leads
            if (in_array($lead['status'], ['ENRICHED', 'QUALIFIED', 'CONTACTED', 'CONVERTED'])) {
                $lead['last_enriched_at'] = Carbon::now()->subDays(rand(1, 15));
            }

            // Add contact dates for CONTACTED/CONVERTED leads
            if (in_array($lead['status'], ['CONTACTED', 'CONVERTED'])) {
                $lead['last_contacted_at'] = Carbon::now()->subDays(rand(1, 7));
            }

            // Add conversion date for CONVERTED leads
            if ($lead['status'] === 'CONVERTED') {
                $lead['converted_at'] = Carbon::now()->subDays(rand(1, 3));
            }

            DB::table('buyer_leads')->insert($lead);
        }

        // Add some additional leads with minimal data to show variety
        $minimalLeads = [
            [
                'business_name' => 'Sydney Fresh Produce Co',
                'category' => 'Wholesale Distributor',
                'postcode' => '2150',
                'state' => 'NSW',
                'status' => 'NEW',
                'discovered_at' => Carbon::now()->subHours(2),
                'created_at' => Carbon::now()->subHours(2),
                'updated_at' => Carbon::now(),
            ],
            [
                'business_name' => 'Parramatta Kitchen Supplies',
                'category' => 'Restaurant Supplier',
                'postcode' => '2150',
                'state' => 'NSW',
                'status' => 'NEW',
                'discovered_at' => Carbon::now()->subHours(5),
                'created_at' => Carbon::now()->subHours(5),
                'updated_at' => Carbon::now(),
            ],
            [
                'business_name' => 'Bankstown Bakery Wholesale',
                'category' => 'Bakery',
                'postcode' => '2200',
                'state' => 'NSW',
                'status' => 'NEW',
                'discovered_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('buyer_leads')->insert($minimalLeads);

        $this->command->info('BulkHunter leads seeded successfully with ' . (count($leads) + count($minimalLeads)) . ' realistic Sydney businesses!');
    }
}